### ISSUE TITLE
To-do List

### ISSUE THREAD

**Issue by mvkovatch3** [SIO-ODF/ctdcal#20]
# To-do
Trying this out instead of having `TODO.md` in repository.

## Codebase cleanup
[![Language grade: Python](https://img.shields.io/lgtm/grade/python/g/cchdo/ctdcal.svg?logo=lgtm&logoWidth=18)](https://lgtm.com/projects/g/cchdo/ctdcal/context:python)
- [x] refactor unnecessary [duplicate/concurrent T/C fitting](https://github.com/cchdo/ctdcal/blob/8dc468680d443b102b5472c73dd6a214caad795e/ctdcal/fit_ctd.py#L308-L377) (#26)
- [x] generalize T/C polyfits to one "smarter" function that work with both (build equation from input coefs) (#26)

### Review/refactor/write tests
[![codecov](https://codecov.io/gh/cchdo/ctdcal/branch/main/graph/badge.svg?token=nB3wG0QCb4)](https://codecov.io/gh/cchdo/ctdcal)
- [ ] `convert.py` ([refactor_convert](https://github.com/cchdo/ctdcal/tree/refactor_convert) branch)
- [x] `ctd_plots.py` (#35)
- [x] `equations_sbe.py` (#15, #36)
- [x] `fit_ctd.py` (#26)
- [x] `flagging.py` (#33)
- [x] `merge_codes.py` (deleted in #39)
- [x] `io.py` (#39)
- [x] `odf_io.py`(#37)
- [ ] `oxy_fitting.py`
- [ ] `process_bottle.py`
- [ ] `process_ctd.py`
- [x] `report_ctd.py` (merged into `odf_io` in #39)
- [ ] `rinko.py`
- [ ] `sbe_reader.py`

---

## CLI tools
- [x] `ctdcal init` (generate default directories ~based on configuration.ini?~)
- [ ] `ctdcal import` (import data)
- [ ] `ctdcal convert` (convert engineering data)
- [x] `ctdcal process` (run processing script)
- [ ] `ctdcal qc` (launch interactive QC)

---

## Documentation
- [x] setup sphinx documentation
- [ ] NumPy docstring for all functions
- [x] API reference (#28)
- [x] new user guide (with [Jupyter notebooks](https://github.com/JamesALeedham/Sphinx-Autosummary-Recursion/tree/master/docs/notebooks)!) (#28)
- [x] make new user guide actually use ctdcal... ~(get test data from CCHDO using [pooch](https://pypi.org/project/pooch/)?)~ (#47)
- [x] auto-publish released versions on PyPI (#30)
- [x] auto-publish tagged versions on Test PyPI (#32)

---

## Improve robustness
- [x] remove hardcoded "expected columns" from `config.py` (check converted file cols)
- [ ] add handling for missing/unused sensors (e.g. Rinko, fluorometer, transmissometer)
- [ ] make codebase less specific to ODF
- [ ] reduce scope of functions
- [ ] allow users to change settings with mutable types ([e.g. dict?](https://stackoverflow.com/a/9158998/13155619))

### Testing
- [x] Review other packages' testing schemes (e.g., [NumPy](https://github.com/numpy/numpy/blob/main/numpy/polynomial/tests/test_polynomial.py), [xarray](https://github.com/pydata/xarray/tree/main/xarray/tests), [pandas](https://github.com/pandas-dev/pandas/tree/master/pandas/tests))
- [x] decide on testing framework (unittest, mypy, hypothesis, etc.) (#33)
- [x] test against multiple OS and python versions (#34)
- [ ] data-driven testing?
- [ ] [static type testing](https://mypy.readthedocs.io/en/stable/existing_code.html)

### Package integration
- [x] black
- [x] flake8
- [x] pre-commit 
- [x] logging (#23)
- [x] pathlib
- [x] pytest <s>unittest (or other testing package)</s>
- [x] click
- [x] gsw (full integration across all modules)
- [x] isort 
- [ ] test Python 3.10 (last tried 2/3/21, failing due to `numpy` it seems)
- [ ] mypy (starting with #39)

---

## Decrease processing time
- [ ] [save fit parameters to file](https://github.com/cchdo/ctdcal/commit/eb1105caed7eb3a2dac1d198afae24dbb30fba20#r54001868) (json?), make option to re-use coefs instead of re-calculating (e.g. slow, iterative oxy fits)
- [ ] parallelization
- [ ] speed up oxygen and rinko modules

---

#### Processing
- [ ] process as group (ODF, PMEL, CSIRO, etc.)
#### Fitting
- [ ] Fit as a function of time to remove drift (e.g., conductivity cell drift)
#### Plotting
- [ ] bathymetry plots
- [ ] pyDIVA section plots (objective mapping)
- [ ] pcolor diff plots (vs. previous years?)
#### Cruise report
- [ ] function for sanitizing bad unicode in .rst files (carriage return, bad greek letters, etc.)
---

## Technical
- [ ] machine learning ([Controlled Abstention Networks (CAN)?](https://github.com/eabarnes1010/controlled_abstention_networks))
- [ ] binary search algorithm for fitting T/C
> Binary search algorithm when fitting T/C - start looking for 2nd degree fit at 1000 db,
then try upwards with min=500 to start. minimum 50 db bins. Optimize based on residuals on all points
and on residuals against y=0 (differences are 0) for pressure range (1000:6000)
possibly fold in some of the data above the pressure range, just to make sure it's not overly throwing out the top)

---

## Miscellaneous
- [ ] standardize flag names with directory names (oxy vs. oxygen, cond vs. conductivity, etc.)
(standardize on WOCE parameter names/relationships where possible, but in a long form)
- [x] config and/or constants file (#25)
- [ ] re-reckon all module names to something better
- [ ] separate all conversions (salts, oxygen) from merging/calibration routines
- [x] [GitHub workflows](https://docs.github.com/en/actions/learn-github-actions)
- [ ] conda packaging
- [ ] [multi-location logging](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-multiple-destinations) (e.g., all messages to log file, only messages >= WARNING to stdout)
- [ ] `quickstart` command to prompt for cruise name, etc. (a la [sphinx-quickstart](https://github.com/sphinx-doc/sphinx/blob/4.x/sphinx/cmd/quickstart.py))

**Comment by Klankers** [comment]
Retiring this to-do list with implementation of #55 .
